apiVersion: v1
kind: Service
metadata:
  name: gymlog
  namespace: colossus-gymlog
  labels:
    app: gymlog
    managed-by: colossus
spec:
  type: ClusterIP
  selector:
    app: gymlog
  ports:
    - port: 80
      targetPort: 80
